"""empty message

Revision ID: 17d8256a7a6
Revises: 2f13c55754b
Create Date: 2015-03-06 12:38:11.986595

"""

# revision identifiers, used by Alembic.
revision = '17d8256a7a6'
down_revision = '2f13c55754b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task', sa.Column('assignee', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('completion_status', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('owner', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('started_status', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('encrypted_password', sa.String(length=60), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'encrypted_password')
    op.drop_column('task', 'started_status')
    op.drop_column('task', 'owner')
    op.drop_column('task', 'due_date')
    op.drop_column('task', 'completion_status')
    op.drop_column('task', 'assignee')
    op.drop_table('comment')
    ### end Alembic commands ###
