"""empty message

Revision ID: 1e144acddd3
Revises: 332fa851edc
Create Date: 2015-03-07 15:05:31.833874

"""

# revision identifiers, used by Alembic.
revision = '1e144acddd3'
down_revision = '332fa851edc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
