"""empty message

Revision ID: f9ebf29f63
Revises: 17d8256a7a6
Create Date: 2015-03-06 15:10:55.180479

"""

# revision identifiers, used by Alembic.
revision = 'f9ebf29f63'
down_revision = '17d8256a7a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('description', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'description')
    ### end Alembic commands ###
